
set_property PACKAGE_PIN A18 [get_ports vga_hsync]
set_property PACKAGE_PIN B18 [get_ports vga_vsync]

set_property PACKAGE_PIN A15 [get_ports {vga_blue[4]}]
set_property PACKAGE_PIN A14 [get_ports {vga_blue[3]}]
set_property PACKAGE_PIN A13 [get_ports {vga_blue[2]}]
set_property PACKAGE_PIN M4 [get_ports {vga_blue[1]}]
set_property PACKAGE_PIN L1 [get_ports {vga_blue[0]}]

set_property PACKAGE_PIN C12 [get_ports {vga_green[5]}]
set_property PACKAGE_PIN D17 [get_ports {vga_green[4]}]
set_property PACKAGE_PIN E17 [get_ports {vga_green[3]}]
set_property PACKAGE_PIN C17 [get_ports {vga_green[2]}]
set_property PACKAGE_PIN C16 [get_ports {vga_green[1]}]
set_property PACKAGE_PIN A16 [get_ports {vga_green[0]}]

set_property PACKAGE_PIN B17 [get_ports {vga_red[4]}]
set_property PACKAGE_PIN B16 [get_ports {vga_red[3]}]
set_property PACKAGE_PIN B14 [get_ports {vga_red[2]}]
set_property PACKAGE_PIN B13 [get_ports {vga_red[1]}]
set_property PACKAGE_PIN B12 [get_ports {vga_red[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]

set_property IOSTANDARD LVCMOS33 [get_ports {d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports pclk]
set_property IOSTANDARD LVCMOS33 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property PACKAGE_PIN V14 [get_ports href]
set_property PACKAGE_PIN V11 [get_ports vsync]
set_property PACKAGE_PIN V15 [get_ports xclk]
set_property PACKAGE_PIN U12 [get_ports pclk]
set_property PACKAGE_PIN U14 [get_ports I2C_SDAT]
set_property PACKAGE_PIN V10 [get_ports I2C_SCLK]

set_property PACKAGE_PIN V17 [get_ports {d[0]}]
set_property PACKAGE_PIN U11 [get_ports {d[1]}]
set_property PACKAGE_PIN U17 [get_ports {d[2]}]
set_property PACKAGE_PIN T13 [get_ports {d[3]}]
set_property PACKAGE_PIN U18 [get_ports {d[4]}]
set_property PACKAGE_PIN U13 [get_ports {d[5]}]
set_property PACKAGE_PIN V16 [get_ports {d[6]}]
set_property PACKAGE_PIN V12 [get_ports {d[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports xclk]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SDAT]


set_property IOSTANDARD LVCMOS33 [get_ports pwdm]
set_property IOSTANDARD LVCMOS33 [get_ports reset_cam]
set_property PACKAGE_PIN U16 [get_ports pwdm]
set_property PACKAGE_PIN T11 [get_ports reset_cam]



set_property IOSTANDARD LVCMOS33 [get_ports air_pressure_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports burn_judge_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports co_judge_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports combustible_judge_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports compass_data_rx]
set_property IOSTANDARD LVCMOS33 [get_ports compass_data_tx]
set_property IOSTANDARD LVCMOS33 [get_ports data_out_speech]
set_property IOSTANDARD LVCMOS33 [get_ports finger_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports finger_data_out]
set_property IOSTANDARD LVCMOS33 [get_ports fire_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports keys_down_in]
set_property IOSTANDARD LVCMOS33 [get_ports keys_left_in]
set_property IOSTANDARD LVCMOS33 [get_ports keys_right_in]
set_property IOSTANDARD LVCMOS33 [get_ports keys_up_in]
set_property IOSTANDARD LVCMOS33 [get_ports light_data_rx]
set_property IOSTANDARD LVCMOS33 [get_ports message_data_tx]
set_property IOSTANDARD LVCMOS33 [get_ports mpu_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_camera]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_x]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_z]
set_property IOSTANDARD LVCMOS33 [get_ports red_lazer_temp_data_rx]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports temp_hum_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uasrt_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports usart_data_out]
set_property IOSTANDARD LVCMOS33 [get_ports voice_data_in]
set_property PACKAGE_PIN R13 [get_ports air_pressure_data_in]
set_property PACKAGE_PIN R11 [get_ports burn_judge_data_in]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN T9 [get_ports co_judge_data_in]
set_property PACKAGE_PIN T15 [get_ports combustible_judge_data_in]
set_property PACKAGE_PIN R15 [get_ports compass_data_rx]
set_property PACKAGE_PIN R18 [get_ports compass_data_tx]
set_property PACKAGE_PIN T8 [get_ports data_out_speech]
set_property PACKAGE_PIN U7 [get_ports finger_data_in]
set_property PACKAGE_PIN U8 [get_ports finger_data_out]
set_property PACKAGE_PIN T6 [get_ports fire_data_in]
set_property PACKAGE_PIN V7 [get_ports keys_down_in]
set_property PACKAGE_PIN R7 [get_ports keys_left_in]
set_property PACKAGE_PIN V6 [get_ports keys_right_in]
set_property PACKAGE_PIN U6 [get_ports keys_up_in]
set_property PACKAGE_PIN R12 [get_ports red_lazer_temp_data_rx]
set_property PACKAGE_PIN R10 [get_ports rst_n]
set_property PACKAGE_PIN U9 [get_ports uasrt_data_in]
set_property PACKAGE_PIN R8 [get_ports usart_data_out]
set_property PACKAGE_PIN V9 [get_ports voice_data_in]

set_property IOSTANDARD LVCMOS33 [get_ports Echo]
set_property PACKAGE_PIN V2 [get_ports Echo]
set_property IOSTANDARD LVCMOS33 [get_ports trig]




set_property IOSTANDARD LVCMOS33 [get_ports angle_z_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports fire_data_out]
set_property IOSTANDARD LVCMOS33 [get_ports seen]
set_property PACKAGE_PIN P18 [get_ports angle_z_data_in]
set_property PACKAGE_PIN U3 [get_ports fire_data_out]


set_property IOSTANDARD LVCMOS33 [get_ports angle_x_data_in]
set_property PACKAGE_PIN L15 [get_ports angle_x_data_in]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pclk_IBUF_BUFG]
set_property PACKAGE_PIN T10 [get_ports temp_hum_rx]
set_property PACKAGE_PIN R16 [get_ports light_data_rx]
set_property PACKAGE_PIN T16 [get_ports mpu_data_in]
set_property PACKAGE_PIN P15 [get_ports message_data_tx]
set_property PACKAGE_PIN T18 [get_ports pwm_camera]
set_property PACKAGE_PIN N14 [get_ports pwm_x]
set_property PACKAGE_PIN P14 [get_ports pwm_z]
set_property PACKAGE_PIN N17 [get_ports seen]
set_property PACKAGE_PIN U4 [get_ports trig]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pclk_IBUF]
